import Foundation

/// One row in the menu's activity log. Generated by `AppListener` on every
/// completed cycle (heard speech → STT → wake filter → action).
struct ActivityEvent: Identifiable, Sendable {
    enum Status: Sendable {
        case ignored                 // no wake phrase — silently dropped
        case dictated(charCount: Int)
        case executed(label: String)
        case deferred(label: String)
        case failed(label: String, reason: String)

        var icon: String {
            switch self {
            case .ignored:    return "ear.trianglebadge.exclamationmark"
            case .dictated:   return "keyboard"
            case .executed:   return "checkmark.circle.fill"
            case .deferred:   return "clock.arrow.circlepath"
            case .failed:     return "xmark.octagon.fill"
            }
        }

        var summary: String {
            switch self {
            case .ignored:                  return "ignored"
            case .dictated(let n):          return "dictated \(n) chars"
            case .executed(let l):          return l
            case .deferred(let l):          return "\(l) (deferred)"
            case .failed(let l, let why):   return "\(l) — \(why)"
            }
        }
    }

    let id = UUID()
    let timestamp: Date
    let heard: String
    let status: Status
}
